### ISSUE TITLE
initial migration depends on existing table

### ISSUE THREAD

**Issue by Astranox** [MPIB/Lagerregal#247]
``./manage.py migrate`` calls get_department_options and get_devicegroup_options in devices/forms.py, which will always fail on initial migration, as no tables exist yet.

removing those calls to the database during migration fixes this issue, migration succeeds.

**Comment by octomike** [comment]
Hi @Astranox - thanks for reporting an issue!

Unfortunately I and also travis with the supplied dockerfile cannot really reproduce the issue. Can you help out by pasting your output?

**Comment by Astranox** [comment]
This happens for me on both branches - develop and master.
Somehow this is different with sqlite - i do use postgres, while the Dockerfile uses sqlite.
Following is the output of a `./manage.py migrate` on an empty postgres database.
Changing the database to sqlite allows for successful table creation.

`$ ./manage.py migrate
Traceback (most recent call last):
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "users_department" does not exist
LINE 1: ..._department"."id", "users_department"."name" FROM "users_dep...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/lagerregal/Lagerregal/urls.py", line 7, in <module>
    from devices.views import *
  File "/srv/lagerregal/devices/views.py", line 32, in <module>
    from devices.forms import IpAddressForm, SearchForm, LendForm, DeviceViewForm, IpAddressPurposeForm
  File "/srv/lagerregal/devices/forms.py", line 208, in <module>
    class DeviceViewForm(forms.Form):
  File "/srv/lagerregal/devices/forms.py", line 215, in DeviceViewForm
    departmentfilter = forms.ChoiceField(choices=get_department_options(),
  File "/srv/lagerregal/devices/forms.py", line 70, in get_department_options
    return DEPARTMENT_OPTIONS + list(Department.objects.all().values_list("id", "name"))
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 122, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 841, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/srv/lagerregal/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "users_department" does not exist
LINE 1: ..._department"."id", "users_department"."name" FROM "users_dep...
                                                             ^
`
