### ISSUE TITLE
Error on populate: users_departmentuser.department_id

### ISSUE THREAD

**Issue by xi** [MPIB/Lagerregal#281]
```
$ .venv/bin/python manage.py populate
Generating buildings
Generating sections
Generating rooms
Generating manufacturers
Generating departments
Generating lagerusers
Generating departmentusers
Traceback (most recent call last):
  File "/home/local/MPIB-BERLIN/bengfort/code/Lagerregal/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/local/MPIB-BERLIN/bengfort/code/Lagerregal/.venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: users_departmentuser.department_id
```

**Comment by xi** [comment]
This is probably because I created an admin (without a main department) before running populate.
